# Generated by Django 3.2.6 on 2021-08-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderlist',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='reminderlistitem',
            name='added_date',
            field=models.DateField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='reminders',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='reminders',
            name='due_date',
            field=models.DateField(verbose_name='due_date'),
        ),
    ]
