# Generated by Django 3.2.6 on 2021-08-06 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_auto_20210805_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminderlistitem',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='reminderlistitem',
            name='reminder',
        ),
        migrations.RemoveField(
            model_name='reminderlistitem',
            name='reminder_list',
        ),
        migrations.AlterField(
            model_name='reminderflags',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', related_query_name='flag', to='reminders.reminders'),
        ),
        migrations.DeleteModel(
            name='ReminderList',
        ),
        migrations.DeleteModel(
            name='ReminderListItem',
        ),
    ]
